// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ1oiFYd3rUsEwEpN6wxEAq9IKdarjCYs',
    appId: '1:967794419288:web:cdf51eabdf2f09cfad0c2d',
    messagingSenderId: '967794419288',
    projectId: 'productapp-1dc2e',
    authDomain: 'productapp-1dc2e.firebaseapp.com',
    storageBucket: 'productapp-1dc2e.appspot.com',
    measurementId: 'G-WVDCK1PW0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB--n-_frwpPB2iinFP8miBsXoO5oBGLI',
    appId: '1:967794419288:android:364b0b23e4825683ad0c2d',
    messagingSenderId: '967794419288',
    projectId: 'productapp-1dc2e',
    storageBucket: 'productapp-1dc2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlwH518brwlNDsdro-XwcO6ZU0gI9Q290',
    appId: '1:967794419288:ios:b26d1d3415c8733dad0c2d',
    messagingSenderId: '967794419288',
    projectId: 'productapp-1dc2e',
    storageBucket: 'productapp-1dc2e.appspot.com',
    iosBundleId: 'com.example.productapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlwH518brwlNDsdro-XwcO6ZU0gI9Q290',
    appId: '1:967794419288:ios:b26d1d3415c8733dad0c2d',
    messagingSenderId: '967794419288',
    projectId: 'productapp-1dc2e',
    storageBucket: 'productapp-1dc2e.appspot.com',
    iosBundleId: 'com.example.productapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ1oiFYd3rUsEwEpN6wxEAq9IKdarjCYs',
    appId: '1:967794419288:web:542f77b83171d113ad0c2d',
    messagingSenderId: '967794419288',
    projectId: 'productapp-1dc2e',
    authDomain: 'productapp-1dc2e.firebaseapp.com',
    storageBucket: 'productapp-1dc2e.appspot.com',
    measurementId: 'G-K51ZR5TTWW',
  );
}
